spring:
  jackson:
    serialization: { WRITE_DATES_AS_TIMESTAMPS: true }
  datasource:
    url: jdbc:mysql://47.113.217.106:3326/test_db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 059089f326ed4bf49fe6a2902a4171f3





logging:
  level:
    admin.zooways.app.mapper: debug